### ISSUE TITLE
Unable to run miQC on Seurat Objects

### ISSUE THREAD

**Issue by zgb963** [greenelab/miQC#14]
Hello,

I've been trying to run miQC on my sample Seurat objects, but from the documentation it appears that in the updated version (I have v1.12.0), you can no longer run miQC on Seurat objects? I only see it being used with SingleCellExperiment objects.

```
liftoff_1_MI5_V1_SO <- filterCells(liftoff_1_MI5_V1_SO, posterior_cutoff = 0.75)
liftoff_2_MI5_V1_SO <- filterCells(liftoff_2_MI5_V1_SO, posterior_cutoff = 0.75)
liftoff_4_MI5_V1_SO <- filterCells(liftoff_4_MI5_V1_SO, posterior_cutoff = 0.75)
liftoff_5_MI5_V1_SO <- filterCells(liftoff_5_MI5_V1_SO, posterior_cutoff = 0.75)
liftoff_6_MI5_V1_SO <- filterCells(liftoff_6_MI5_V1_SO, posterior_cutoff = 0.75)
liftoff_7_MI5_V1_SO <- filterCells(liftoff_7_MI5_V1_SO, posterior_cutoff = 0.75)
liftoff_8_MI5_V1_SO <- filterCells(liftoff_8_MI5_V1_SO, posterior_cutoff = 0.75)
# Error: unable to find an inherited method for function ‘colData’ for signature ‘x = "Seurat"’

```

I also noticed that the `RunMiQC` function is no longer available and has been replaced with `filterCells`. When I ran miQC earlier this year on single cell data, I was able to run miQC version 1.6.0 without any issues. I followed this [tutorial](https://htmlpreview.github.io/?https://github.com/satijalab/seurat-wrappers/blob/master/docs/miQC.html). 

```
seurat.obj_1_MI1_S3 <- RunMiQC(seurat.obj_1_MI1_S3, percent.mt = "percent.mt", nFeature_RNA = "nFeature_RNA", posterior.cutoff = 0.75, model.slot = "flexmix_model")
seurat.obj_2_MI1_S4 <- RunMiQC(seurat.obj_2_MI1_S4, percent.mt = "percent.mt", nFeature_RNA = "nFeature_RNA", posterior.cutoff = 0.75, model.slot = "flexmix_model")
seurat.obj_3_C_MI2_S1 <- RunMiQC(seurat.obj_3_C_MI2_S1, percent.mt = "percent.mt", nFeature_RNA = "nFeature_RNA", posterior.cutoff = 0.75, model.slot = "flexmix_model")
seurat.obj_4_D_MI2_S2 <-RunMiQC(seurat.obj_4_D_MI2_S2, percent.mt = "percent.mt", nFeature_RNA = "nFeature_RNA", posterior.cutoff = 0.75, model.slot = "flexmix_model")
seurat.obj_4_MI1_S5 <- RunMiQC(seurat.obj_4_MI1_S5, percent.mt = "percent.mt", nFeature_RNA = "nFeature_RNA", posterior.cutoff = 0.75, model.slot = "flexmix_model")
seurat.obj_5_MI1_S6 <- RunMiQC(seurat.obj_5_MI1_S6, percent.mt = "percent.mt", nFeature_RNA = "nFeature_RNA", posterior.cutoff = 0.75, model.slot = "flexmix_model")
seurat.obj_7_MI1_S7 <- RunMiQC(seurat.obj_7_MI1_S7, percent.mt = "percent.mt", nFeature_RNA = "nFeature_RNA", posterior.cutoff = 0.75, model.slot = "flexmix_model")

```

I also tried installing a version of miQC but that also didn't work. Also uninstalling and reinstalling didn't work. Is there a way I can run miQC on Seurat objects? Or would i need to convert the Seurat object to a SingleCellExperiment object? Does the conversion alter the data?

**Comment by stephaniehicks** [comment]
Hi, I believe you need to submit a GitHub issue on the Seurat website. Our package has always supported `SingleCellExperiment` objects and then I believe Seurat created a wrapper of our package to extend it for `Seurat` objects. The wrapper code you are seeking is not in this repository. Therefore, we are unable to help. Hope this helps clarify!

**Comment by zgb963** [comment]
> Hi, I believe you need to submit a GitHub issue on the Seurat website. Our package has always supported `SingleCellExperiment` objects and then I believe Seurat created a wrapper of our package to extend it for `Seurat` objects. The wrapper code you are seeking is not in this repository. Therefore, we are unable to help. Hope this helps clarify!

Hi Stephanie, thanks for your reply! I was able to get the `RunMiQC` function to run by installing the `R.utils` and `SeuratWrappers` packages.

```
install.packages("R.utils")
remotes::install_github('satijalab/seurat-wrappers')
```
